### PR TITLE
Add mouse Optimus subscription

### PR DESCRIPTION
**Pull request by ambrosejcarr**
Uses Strategy A here: https://docs.google.com/document/d/1ZwaroR1m2V2Rirvz7b6m7YFO_W6Hav9m0P5m4FDNf-g/edit

### CODE REVIEW

**Comment by samanehsan** [comment]
As discussed with @ambrosejcarr in person, it would be easier to implement strategy B in the document for SmartSeq2 and Optimus and then update the subscriptions to match on either human or mouse data

**Review by rexwangcc — APPROVED** [review]
LGTM

**Comment by ambrosejcarr** [comment]
@rexwangcc @samanehsan How has implementation of strategy B been going? Should we merge this or wait?

**Comment by rexwangcc** [comment]
@ambrosejcarr It's still ongoing and @ApChagi is working on it:
- https://github.com/HumanCellAtlas/metadata-api/pull/80
- https://github.com/HumanCellAtlas/metadata-api/pull/81
- https://github.com/HumanCellAtlas/pipeline-tools/commit/33922b8bb320edee55a725bb265db8dfbdc12359

I think we might want to wait at this point? 🤔

**Comment by ambrosejcarr** [comment]
Ok. There are downstream dependencies that require some time to complete their work prior to the end of the quarter (at least the Matrix service). Do you have an estimate of when your work will be completed? It seems like we have an otherwise working solution that could kick off some workflows so I am hesitant to wait too long because it adds pressure on other teams.

**Comment by jkaneria** [comment]
The team member working on the mouse reference ticket is out today so I'm not sure how much work is left. We could manually run a mouse sample through the Optimus pipeline so we could unblock downstream teams immediately.

**Comment by mckinsel** [comment]
@jkaneria yeah manually running one would be helpful.

**Comment by jkaneria** [comment]
@rexwangcc is kicking it off now.

**Comment by ambrosejcarr** [comment]
@samanehsan @rexwangcc I suspect this PR can be closed, so am going to close it. Feel free to reopen if I'm incorrect.

**Pull request closed without merging**
